# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
  locale: 'de'
  app_state_country: '%env(APP_STATE_COUNTRY)%'
  filebase: '%kernel.project_dir%/var/data'
  documents_directory: '%filebase%/documents'
  food_survey_directory: '%filebase%/food_survey'

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

  # controllers are imported separately to make sure services can be injected
  # as action arguments even if you don't extend any base controller class
  App\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones
  App\EventListener\CheckCurrentSchoolListener:
    tags:
      - { name: kernel.event_listener, event: kernel.controller }

  App\EventListener\CheckTempPasswordListener:
    tags:
      - { name: kernel.event_listener, event: kernel.controller }

  App\Repository\SchoolRepository:
    arguments:
      $app_state_country: '%env(APP_STATE_COUNTRY)%'

  app.menu_builder:
    class: App\Menu\MenuBuilder
    arguments: ["@knp_menu.factory"]

  app.main_menu:
    class: Knp\Menu\MenuItem # the service definition requires setting the class
    factory: ["@app.menu_builder", createMainMenu]
    arguments: ["@request_stack",]
    tags:
      - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu

  Knp\Menu\MenuItem: '@app.main_menu'

  security.authentication.login_handler:
    class: 'App\Security\LoginListener'
    arguments: ["@security.authorization_checker", "@doctrine.orm.entity_manager"]
    tags:
      - { name: 'kernel.event_listener', event: 'security.interactive_login' }

  App\Service\IconHelper:
    arguments:
      $svgDir: '%kernel.project_dir%/node_modules/@fortawesome/fontawesome-pro/svgs/solid'
      $pngCacheDir: '%kernel.project_dir%/var/cache/icons'

  App\Twig\PdfIconExtension:
    arguments:
      $helper: '@App\Service\IconHelper'
    tags: [ 'twig.extension' ]
